### PR TITLE
Created guideline for contributing to documentation

### PR DESCRIPTION
**Pull request by dotslash21**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

Fixes: #56

### CODE REVIEW

**Comment by dotslash21** [comment]
@darkmatter18, I've created the guideline to the best of my knowledge about the project. Let me know if something is missing or needs to be changed.

**Review by darkmatter18 — CHANGES_REQUESTED** [review]
@dotslash21 Everything is so good. But can you please add the guideline of the local setup, like how to install and run the docs locally? 

These links will help you
1. https://squidfunk.github.io/mkdocs-material/getting-started/
2. https://squidfunk.github.io/mkdocs-material/creating-your-site/

**Comment by dotslash21** [comment]
Hey @darkmatter18, If you want to include a step by step guide then the best place IMO would be in the docs itself. If we create a `Contributing` page in the docs and link to it from `CONTRIBUTING.md` then the size of `CONTRIBUTING.md` will be optimal. Currently it is perfect sized, but if any more text is added it'll be too long.

Anyways, the final call is up to you @darkmatter18.

**Comment by darkmatter18** [comment]
@dotslash21 Okkk. I like your idea. Then let's leave this PR here and make a new issue for that. Thanks a lot. 🎉🎊

**Review by darkmatter18 — APPROVED** [review]

**Pull request merged**
